pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code from Git...'
                checkout scm
                // OR if you want to hardcode repo:
                 git branch: 'main', url: 'https://github.com/naveenroy65/task/edit/main/Java-CICD-Demo_1.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'mvn package'
                echo 'Application packaged successfully!'
            }
        }
    }
}
